name: Documentation request
description: Suggest a documentation change to Redpanda
body:
  - type: textarea
    attributes:
      label: Issue Description
      description: What problem does this issue solve for customers?
        Who is the audience for this update? For example, cluster admins, or developers?
        Do you know the context in which users will likely search for this content? If so, share it.
        If this is a new feature, add a label for the version in which the update is expected.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Updates to existing documentation
      description: Provide the URL of the page(s) to which the updates apply.
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Is this a new feature?
      options:
        - label: Yes