name: Documentation request
description: Suggest a documentation change to Redpanda
body:
  - type: textarea
    attributes:
      label: Issue Description
      description: What problem does this issue solve for customers? Who is the
        audience for this update? For example, cluster admins, or developers? Do
        you know the context in which users will likely search for this content?
        If so, share it. If this is a new feature, add a label for the version
        in which the update is expected.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Updates to existing documentation
      description: Provide the URL of the page(s) to which the updates apply.
  - type: checkboxes
    attributes:
      label: Is this a new feature?
      options:
        - label: "Yes"
  - type: textarea
    attributes:
      label: New feature additional info
      description: If this is a new feature, provide material that will help the writer draft the new or updated content. If an issue only includes the name of a feature and release, it will be marked “More Info Needed” or “Blocked”.
      value: |
        1. Links to internal wikis, PRDs, design docs, KIPs, training material, or slide decks. 
        2. Links to engineering PRs that implement the update. 
        3. Links to blog posts, if applicable. 
        4. Identify specific Slack channels that the writer can join to get more details about the feature. 
        5. Links to Slack conversations (RP and RP Community) about the issue. 
        6. Names of SMEs who can answer questions and act as reviewers (at least one engineer and one PM). 
        7. Any additional information that will be of use to the writer.

        